### ISSUE TITLE
サクラエディタ本体のPR、Issueのラベル付け方法を明確にする

### ISSUE THREAD

**Issue by takke** [sakura-editor/changelog-sakura#3]
github_changelog_generator で CHANGELOG.md を生成するために、サクラエディタ本体の PR や Issue のラベル付けをドキュメント化しておいたほうがいいと思います。

PR という意味では https://github.com/sakura-editor/sakura/wiki/11.SakuraEditor_PRGuide あたりかなと思いましたが、PR を送るときに私のような部外者はラベルを付けられないので、https://github.com/sakura-editor/sakura/wiki 配下にラベルの付け方を解説した別の記事があってもいいかと思います。既にあったらすみません。

**Comment by KENCHjp** [comment]
あと、何を加えて何を除外するかですが、あれどっかにかいたかもしれませんが、

enhancement
bug
を対象にするけれども、
management
question
refactoring
Release
は除外って感じかなと。
抽出されたものを見たのですが、まだつけ方結構甘いかったですね(笑)

**Comment by takke** [comment]
今のところのバッチファイルの設定では、

https://github.com/sakura-editor/changelog-sakura/pull/1/files#diff-3ea088be16b8edc4ebf1fa1d8626038fR10
```bat
set EXCLUDELABELS=duplicate,question,invalid,wontfix,CI,management,refactoring
```
のように除外しています。

そして、github_changelog_generator としては、「enhancement」「bug」ラベルをまとめ、「それ以外のIssue」「それ以外のPR」という分類をするようです。

**Comment by KENCHjp** [comment]
>今のところのバッチファイルの設定では、

了解です。リリースのときに調整とラベルつけをそれなりにしっかりやらないとですね。
IssueはしかとでPRだけでいいかなっておもってますが。。。
（Issueは聞いただけで特にソースにコミットされてないものもあるかと思うので）

**Comment by KENCHjp** [comment]
specification change
も拾わないとだめそうっすね。

**Comment by takke** [comment]
https://github.com/sakura-editor/sakura/wiki/CHANGELOG.md%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6 の wiki にまとめておきました。
