### ISSUE TITLE
定期実行の仕組みを導入する

### ISSUE THREAD

**Issue by takke** [sakura-editor/changelog-sakura#6]
#1 のレビュー結果として立てます。

https://github.com/sakura-editor/management-forum/issues/53#issuecomment-445054868 に書かれていた定期実行を入れてもらえると、#5 と組み合わせて CHANGELOG.md が定期的に更新されるようになるのでとっても嬉しいです。

**以下追記**

## 参考サイト

- https://www.appveyor.com/docs/build-configuration/#scheduled-builds
- https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/

## appveyor への依頼

https://github.com/appveyor/ci/issues/2764

## 実行スケジュール

日本時間 AM 3:00 (2018/12/13 現在)
https://github.com/sakura-editor/changelog-sakura/issues/6#issuecomment-446567219

**Comment by m-tmatma** [comment]
日本時間(JST)のam 3:00 ぐらいに実行したらいいんではないかと思います。
多分その時間はみんな寝ているはずなので。

**Comment by m-tmatma** [comment]
↑ [appveyor はカナダの会社みたいなので](https://www.appveyor.com/about/) 解釈で誤解のないように
明示的に日本のタイムゾーン(JST +0900)を指定して書くか、あるいは UTC で表現して
明示的に UTC というのを伝えるとがいいと思う。

**Comment by m-tmatma** [comment]
依頼しました。
https://github.com/appveyor/ci/issues/2764

**Comment by m-tmatma** [comment]
有効にしてもらいました。

**Comment by m-tmatma** [comment]
https://www.appveyor.com/docs/build-configuration/#scheduled-builds
によると `Schedule hour values should be UTC.` とある。

https://github.com/atifaziz/NCrontab/wiki/Crontab-Expression
に設定方法が記載されている。
普通の cron と同じぽい。

`MINUTES HOURS DAYS MONTHS DAYS-OF-WEEK`

→ 毎日日本時間の午前 3:00 に実行したい。 
→ `0 3 * * *` (日本時間の場合) 
→ `0 18 * * *` (UTCの場合)

**Comment by m-tmatma** [comment]
ちゃんと動くか調べるためにとりあえず日本時間の午前 7:45 に起動するように設定してみる。

→ `45 7 * *` (日本時間 +0900 の場合)
→ `45 22 * * *` (UTCの場合)

**Comment by m-tmatma** [comment]
> ちゃんと動くか調べるためにとりあえず日本時間の午前 7:45 に起動するように設定してみる。
> 
> → `45 7 * *` (日本時間 +0900 の場合)
> → `45 22 * * *` (UTCの場合)

以下で自動的にビルドが走るのを確認しました。
https://ci.appveyor.com/project/sakuraeditor/changelog-sakura/builds/20941794

**Comment by m-tmatma** [comment]
> → 毎日日本時間の午前 3:00 に実行したい。

これでいいと思いますか?

**Comment by takke** [comment]
> これでいいと思いますか?

いいと思います！

**Comment by m-tmatma** [comment]
> → 毎日日本時間の午前 3:00 に実行したい。
> → `0 3 * * *` (日本時間の場合)
> → `0 18 * * *` (UTCの場合)

設定しました。

**Comment by m-tmatma** [comment]
↑ 上記が動けば、markdown に実行スケジュール記載予定。

**Comment by berryzplus** [comment]
> ↑ 上記が動けば、markdown に実行スケジュール記載予定。

お疲れ様です。やっぱJSTで指定したいですよね。JapanStandardTime...
最近夜更かししすぎなので今夜は寝ます :smile:

**Comment by m-tmatma** [comment]
> > → 毎日日本時間の午前 3:00 に実行したい。
> > → `0 3 * * *` (日本時間の場合)
> > → `0 18 * * *` (UTCの場合)
> 
> 設定しました。

動いた。
https://ci.appveyor.com/project/sakuraeditor/changelog-sakura/builds/20963572

**Comment by m-tmatma** [comment]
> ↑ 上記が動けば、markdown に実行スケジュール記載予定。

#12 で追加しました。

**Comment by takke** [comment]
ありがとうございます。定期実行されたのが確認できたので閉じておきます。
