### ISSUE TITLE
ライセンスを決める

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/changelog-sakura#8]
このリポジトリは新規に作成したものなので、
基本的に適用ライセンスは自由に決められる。

他のプロジェクトで安心して、流用できるように
ライセンスを決めておく。

**Comment by m-tmatma** [comment]
GPL 関連のライセンスは避けたいと思います。

**Comment by takke** [comment]
sakura 本体は zlib で、github-changelog-generator は MIT なんですね。

```Copyright (C) 2018 Sakura Editor Organization``` であればどれでもいいかと思います。

**Comment by berryzplus** [comment]
MITに一票 👍

**Comment by KageShiron** [comment]
github-changelog-generatorもMITなので、MITで良いかと思います。

**Comment by m-tmatma** [comment]
#10 で PR 作成しました。
MIT ライセンスで。

**Comment by m-tmatma** [comment]
#10 をマージしました。
